
    version: '3.8'

    services:
      db:
        image: postgres:14
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - "5432:5432"
        volumes:
          - pg_data:/var/lib/postgresql/data
          - ./table.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

      etl_app:
        build: .
        restart: always
        environment:
          API_URL: https://jsonplaceholder.typicode.com/posts
          DB_HOST: db
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
        depends_on:
          db:
            condition: service_healthy

    volumes:
      pg_data: